# Cross Val score checking

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")

In [16]:
df = sns.load_dataset("titanic")

In [17]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [19]:
df.drop("deck", axis =1 , inplace=True)

In [20]:
df['age'].fillna(df['age'].mean(),inplace=True)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 14 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  embark_town  889 non-null    object
 12  alive        891 non-null    object
 13  alone        891 non-null    bool
dtypes: bool(2), category(1), float64(2), int64(4), object(5)
memory usage: 79.4+ KB

In [22]:
df.drop(['alone','embark_town','who','class','alive'], axis=1,inplace=True)

In [23]:
df.head()

   survived  pclass     sex   age  sibsp  parch     fare embarked  adult_male
0         0       3    male  22.0      1      0   7.2500        S        True
1         1       1  female  38.0      1      0  71.2833        C       False
2         1       3  female  26.0      0      0   7.9250        S       False
3         1       1  female  35.0      1      0  53.1000        S       False
4         0       3    male  35.0      0      0   8.0500        S        True

In [24]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])
df['embarked'] = le.fit_transform(df['embarked'])

In [25]:
df.head()

   survived  pclass  sex   age  sibsp  parch     fare  embarked  adult_male
0         0       3    1  22.0      1      0   7.2500         2        True
1         1       1    0  38.0      1      0  71.2833         0       False
2         1       3    0  26.0      0      0   7.9250         2       False
3         1       1    0  35.0      1      0  53.1000         2       False
4         0       3    1  35.0      0      0   8.0500         2        True

In [27]:
df = df.astype(int)

In [28]:
df.head()

   survived  pclass  sex  age  sibsp  parch  fare  embarked  adult_male
0         0       3    1   22      1      0     7         2           1
1         1       1    0   38      1      0    71         0           0
2         1       3    0   26      0      0     7         2           0
3         1       1    0   35      1      0    53         2           0
4         0       3    1   35      0      0     8         2           1

In [29]:
X= df.drop("survived", axis=1)
y = df['survived']

In [35]:
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
model_svm = SVC()
model_svm.fit(X_scaled , y)

SVC()

In [36]:
scores = cross_val_score(model_svm , X_scaled, y, cv=5,scoring = 'accuracy' )

In [37]:
scores

array([0.83240223, 0.81460674, 0.81460674, 0.81460674, 0.85955056])

In [38]:
scores.mean()

np.float64(0.827154604230745)